### ISSUE TITLE
Tf2:freeplay needs these playlists as options

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#12]
Tf2:freeplay needs these playlists as options.
mapcycle_LL_all.txt
mapcycle_LL_arena.txt
mapcycle_LL_cp.txt
mapcycle_LL_ctf.txt
mapcycle_LL_koth.txt
mapcycle_LL_ph.txt
mapcycle_LL_pl.txt
mapcycle_LL_plr.txt

**Comment by dudleycodes** [comment]
@JustinBenedick - I need you to list the first (default) map associated with each playlist before I can fix this.

**Comment by JustinBenedick** [comment]
replace " +map (mapname) " with +randommap and its all good.
