### ISSUE TITLE
Verify TF2Ware launch string is correct

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/Snippet-Generator#19]
If correct close issue. If not describe what's wrong and tag me.

**Comment by JustinBenedick** [comment]
The server launches within the container but it crashes, needs some time to figure out cause.

**Comment by dudleycodes** [comment]
But the launch string itself looks good?

**Comment by JustinBenedick** [comment]
String looks good. Server launches. And in vm it does crash with update. So it does looks like a conflict between  sm and new version of tf2.

**Comment by dudleycodes** [comment]
Ok; I'm going to close *this* issue. Please open the crash/sm issue on the appropriate repo and work on it from there.

https://github.com/LacledesLAN/gamesvr-srcds-tf2-ware
