### ISSUE TITLE
"-insecure +ip 0.0.0.0 -port 27015 +rcon_password "an"  is in blindfrag

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#20]
I just noticed that "-insecure +ip 0.0.0.0 -port 27015" is in the blind frag launch string. Its not nessacary for docker launch strings. 

Sample of the current launch string. 
`docker run -d --cpuset-cpus="1" --name TF2BlindFrag_Sun13h21m09s -p=172.30.10.36:1200:1200/udp -p=172.30.10.36:1500:1500/udp -p=172.30.10.36:3005:3005/udp -p=172.30.10.36:3101:3101/udp -p=172.30.10.36:28960:28960/udp -p=172.30.10.36:3478-3479:3478-3479/udp -p=172.30.10.36:4379-4380:4379-4380/udp -p=172.30.10.36:26900-26915:26900-26915/udp -p=172.30.10.36:27000-27030:27000-27030/udp -p=172.30.10.36:27000-27050:27000-27050/tcp lacledeslan/gamesvr-srcds-tf2-blindfrag:linux ./srcds_run -port 27015 -game tf +maxplayers 24 -console -usercon +hostname "Laclede's_LAN_TF2_Blind_Frag" +sv_password "towers2" +map koth_harvest_final +maplist mapcycle_quickplay_koth -insecure +ip 0.0.0.0 -port 27015 +rcon_password "[REDACTED]" `

**Comment by dudleycodes** [comment]
To clarify, remove all three arguments? `-insecure`, `+ip 0.0.0.0`, and `-port 27015"`.

**Comment by JustinBenedick** [comment]
yes
