### ISSUE TITLE
Need '7 Days to Die' freeplay launch string

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/Snippet-Generator#21]
While you're at it please audit/build-out the image `gamesvr-srcds-7daystodie-freeplay`

**Comment by JustinBenedick** [comment]
Very basic script 

`~/gameserver/7DaysToDieServer.x86_64 -configfile=serverconfig.xml -logfile 7DaysToDie_Data/output_log.txt $@`

**Comment by dudleycodes** [comment]
Ty, will close issue when I've gotten it into the code base for snippet gen
