### ISSUE TITLE
Need black mesa section

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#26]
Need black mesa section

Launch string
srcds_run -game bms tf +sv_pure 0 +map gasworks +maxplayers 24 +sv_lan 1 -console -usercon +hostname "LacledesLAN_Black_Mesa" -insecure +ip 0.0.0.0 +ip 10.0.0.1 -port 27015 +rcon_password "(REDACTED)"

Mam list list
dm_bounce.bsp
dm_chopper.bsp
dm_crossfire.bsp
dm_gasworks.bsp
dm_lambdabunker.bsp
dm_power.bsp
dm_rail.bsp
dm_stack.bsp
dm_stalkyard.bsp
dm_subtransit.bsp
dm_undertow.bsp

**Comment by dudleycodes** [comment]
@JustinBenedick - please verify this was implemented correctly in latest commit 0f5cddd46639c840d1acc2e3bfedf1d2c9bea811

If correct please close issue; otherwise let me know what's wrong.

**Comment by JustinBenedick** [comment]
Sever launches correctly
