### ISSUE TITLE
as of 0f5cd none of the drop down menus work in edge or IE

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#29]
as of 0f5cd none of the drop down menus work. They are all blank in MS edge and IE

https://i.imgur.com/OhvcwTg.png

**Comment by dudleycodes** [comment]
This seems to be the issue:

> Although NodeList is not an Array, it is possible to iterate on it using forEach().  Several older browsers have not implemented this method yet.

Source: https://developer.mozilla.org/en-US/docs/Web/API/NodeList
