### ISSUE TITLE
Need maplist for GESource

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/Snippet-Generator#31]
@JustinBenedick can you provide me a list of GESource maps for the dropdown? From there I'll get it integrated. Thanks!

**Comment by JustinBenedick** [comment]
ge_archives
ge_archives_classic
ge_aztec
ge_basement
ge_basement_classic
ge_bunker
ge_bunker_classic
ge_casino
ge_caverns
ge_caves
ge_complex
ge_complex_classic
ge_control
ge_cradle
ge_dam
ge_depot
ge_egyptian
ge_facility
ge_facility_backzone
ge_facility_classic
ge_library_classic
ge_runway
ge_silo
ge_stack_classic
ge_temple_classic
ge_transition
