### ISSUE TITLE
Need maplist for Sven Co-Op

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/Snippet-Generator#32]
@JustinBenedick can you provide me a list of Sven Co-Op maps for the dropdown? From there I'll get it integrated. Thanks!

**Comment by JustinBenedick** [comment]
abandoned
BlackMesaEPF
bm_sts
crystal
crystal2
ctf_warforts
deadsimpleneo2
desertcircle
fortified1
hl_c00
hl_c01_a1
hl_c01_a2
hl_c02_a1
hl_c02_a2
hl_c03
hl_c04
hl_c05_a1
hl_c05_a2
hl_c05_a3
hl_c06
hl_c07_a1
hl_c07_a2
hl_c08_a1
hl_c08_a2
hl_c09
hl_c10
hl_c11_a1
hl_c11_a2
hl_c11_a3
hl_c11_a4
hl_c11_a5
hl_c12
hl_c13_a1
hl_c13_a2
hl_c13_a3
hl_c13_a4
hl_c14
hl_c15
hl_c16_a1
hl_c16_a2
hl_c16_a3
hl_c16_a4
hl_c17
hl_c18
hl_t00
hplanet
incoming
infested
infested2
intruder
judgement
last
last2
last3
last4
mommamesa
osprey
polar_rescue
quarter
sandstone
sc_another
sc_doc
sc_mazing
sc_persia
sc_psyko
sc_robination_revised
sc_tetris1
sc_tetris2
sc_tetris3
sc_tetris4
sc_tetris5
sc_tetris6
-sp_campaign_portal
stadium4
svencoop1
svencoop2
tf_original
th_ep1_00
th_ep1_01
th_ep1_02
th_ep1_03
th_ep1_04
th_ep1_05
th_ep2_00
th_ep2_01
th_ep2_02
th_ep2_03
th_ep2_04
th_ep3_00
th_ep3_01
th_ep3_02
th_ep3_03
th_ep3_04
th_ep3_05
th_ep3_06
th_ep3_07
toadsnatch
toonrun1
toonrun2
toonrun3
turretfortress
uplink
yabma
