### ISSUE TITLE
Need to rivert to stock csgo map groups for spring 2018 event 

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#37]
need to use this playlist for spring 2018

CLASSIC 
map group: "mg_active"

"de_inferno"	""
"de_train"		""
"de_mirage"		""
"de_nuke"		""
"de_cbble"		""
"de_overpass"	""
"de_cache"		""

ARMS RACE

map group: "mg_armsrace"

"de_lake"			""
"de_stmarc"			""
"de_safehouse"		""
"ar_shoots"			""
"ar_baggage"		""
"ar_monastery"		""

DEATHMATCH
mapgroup: "mg_deathmatch"

"de_dust2"			""
"de_inferno"		""
"de_mirage"			""
"de_cbble"			""
"de_overpass"		""
"de_dust"			""
"de_aztec"			""
"de_nuke"			""
"de_vertigo"		""
"cs_militia"		""
"cs_assault"		""
"cs_office"			""
"cs_italy"			""
"de_lake"			""
"de_stmarc"			""
"de_sugarcane"		""
"de_bank"			""
"de_safehouse"		""
"de_shortdust"		""
"ar_shoots"			""
"ar_baggage"		""
"ar_monastery"		""

**Comment by JustinBenedick** [comment]
no idea why but "de_vertigo" "" is not in stock server

**Comment by dudleycodes** [comment]
@JustinBenedick  de_vertigo removed in 8c84d5b
