### ISSUE TITLE
cs:go freeplay deathmatch server needs maps added

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#4]
CSGO freeplay deathmatch string needs these maps added. 

cs_agency
cs_assault
cs_backalley
cs_cruise
cs_downtown
cs_insertion
cs_italy
cs_militia
cs_motel
cs_office
cs_rush
cs_thunder
cs_workout
de_austria
de_bank
de_canals
de_lake
de_lite
de_nuke_se
de_safehouse
de_shortdust
de_shorttrain
de_stmarc
de_sugarcane
de_thrill

**Comment by dudleycodes** [comment]
Already had `cs_assault`, `cs_italy`, `cs_militia`, `cs_office`, `de_bank`, `de_lake`, `de_safehouse`, `de_shortdust`, `de_shorttrain`, `de_stmarc`, and `de_sugarcane`.
