### ISSUE TITLE
Need updated map lists for csgo

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#40]
Classic server

Map group for  ll_bomb will use the following maps
de_aztec
de_blackgold
de_castle
de_cbble
de_dust
de_dust2
de_inferno
de_mist
de_nuke
de_overgrown
de_overpass
de_train
de_vertigo
cs_agency
cs_downtown
cs_museum"
cs_siege
de_prodigy
de_ruins
de_season
de_tulip
de_vegas_csgo_v7

Test server 
Map group ll_orange will need to use the following maps 

clienttest-pillar
poolday

**Comment by dudleycodes** [comment]
Closed.  Please verify @JustinBenedick
