### ISSUE TITLE
Need removal of  flexable 'server name" text boxes

### ISSUE THREAD

**Issue by JustinBenedick** [LacledesLAN/Snippet-Generator#7]
Need removal of all flexible 'server name" text boxes. Each server needs to have the server name replaced with hard coded server names like "Laclede's LAN TF2 Freeplay"

**Comment by dudleycodes** [comment]
- [ ] CS:GO Freeplay > Arms Race
- [ ] CS:GO Freeplay > Classic
- [ ] CS:GO Freeplay > Deathmatch
- [ ] Half-Life 2: Deathmatch
- [ ] TF2 > Team Fortress 2
- [ ] TF2 > Blind Frag
